# Generated by Django 4.2.5 on 2024-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.CharField(max_length=255)),
                ('number_contract', models.CharField(max_length=255)),
                ('start_contract', models.DateField()),
                ('end_contract', models.DateField()),
                ('date_contract', models.DateField()),
                ('tenant_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('tenant_r_s', models.CharField(max_length=255)),
                ('type_of_contract', models.CharField(max_length=255)),
                ('tax_on_ad', models.BooleanField()),
                ('in_work', models.BooleanField()),
                ('close', models.BooleanField()),
                ('comment', models.CharField(max_length=255)),
                ('number_contract_in_check', models.CharField(max_length=255)),
                ('main_contract', models.CharField(max_length=255)),
                ('main_lot', models.CharField(max_length=255)),
            ],
        ),
    ]
