# Generated by Django 4.2.5 on 2024-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='close',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='in_work',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tax_on_ad',
            field=models.CharField(max_length=255),
        ),
    ]
